# Generated by Django 4.2.6 on 2023-10-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(
                help_text="Required. Enter a valid email address",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        help_text="Specify the name of the course feedback for",
                        max_length=50,
                    ),
                ),
                (
                    "course_code",
                    models.CharField(help_text="Specify course code", max_length=10),
                ),
                (
                    "professor",
                    models.CharField(
                        help_text="Who teaches the course?", max_length=100
                    ),
                ),
                ("feedback_text", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
