# Generated by Django 4.2.6 on 2023-10-15 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_alter_appuser_email_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppUser",
        ),
    ]
