# Generated by Django 4.2.7 on 2023-11-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_delete_appuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(
                        help_text="The Course code",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person teaching the course. Could the the Professor or TA",
                        max_length=255,
                    ),
                ),
                (
                    "instructor_type",
                    models.CharField(
                        choices=[
                            ("TA", "TA"),
                            ("Professor", "professor"),
                            ("Asst. Professor", "asst. professor"),
                            ("Dr", "dr"),
                            ("Mr", "mr"),
                            ("Miss", "miss"),
                        ],
                        default="Professor",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
